config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  namespace :user do
    resource :cookies, only: %i(update)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
end

app/controllers/user/cookies_controller.rb
# frozen_string_literal: true
class User
  class CookiesController < ApplicationController
    def update
      cookies.permanent[:cookies_policy_accepted] = true
      current_user&.update(cookies_policy_accepted: true)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <%= "Welcome #{current_user.email}" %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
  <br />
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/layouts/_cookies_banner.html.erb
<%= button_to '>>>> Here <<<<', user_cookies_path, id: 'accept_cookies', remote: true, method: :patch %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authenticity</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <% if !cookies[:cookies_policy_accepted] && !current_user&.cookies_policy_accepted %>
      <%= render 'layouts/cookies_banner' %>
    <% end %>
  </body>
</html>

app/views/user/cookies/update.js.erb
alert('Success!!');
document.getElementById('accept_cookies').remove();